### ISSUE TITLE
lack of due date field for addCard function

### ISSUE THREAD

**Issue by hyzhak** [norberteder/trello#27]
https://developers.trello.com/advanced-reference/list#post-1-lists-idlist-cards

**Comment by sinisterstuf** [comment]
From the first line of [README.md](../blob/master/README.md):

> Please feel free to add any other pieces you need! :)

A pull request would probably good. Although it looks like no pull requests have been accepted for almost a year 😢 so I'm not sure how actively maintained the project is.

**Comment by norberteder** [comment]
Pull requests are accepted, of course.

**Comment by cleydyr** [comment]
https://github.com/norberteder/trello/pull/50

**Comment by norberteder** [comment]
Available in version 0.8.0. Thank you all.
