### ISSUE TITLE
Module installed from npm does not contain getMember function

### ISSUE THREAD

**Issue by singhshashi** [norberteder/trello#28]
The following code which is there in the source tree at https://github.com/norberteder/trello/blob/master/main.js line 163-165

```
Trello.prototype.getMember = function(memberId, callback) {
    return makeRequest(rest.get, this.uri + '/1/member/' + memberId, {query: this.createQuery()}, callback);
}
```

is not there in the main.js of the node module I installed using npm install trello. 

dependency entry in package.json after npm install trello is 

  "trello": "^0.5.1",

Thus I am unable to get the member details.

**Comment by emcniece** [comment]
This can be avoided with `npm install github:norberteder/trello`. Still needs to be fixed though.

**Comment by norberteder** [comment]
New version 0.6.0 published to npm. `getMember`  should be available now.
