### ISSUE TITLE
Update link to generate token, app secret and app key

### ISSUE THREAD

**Issue by karlpokus** [norberteder/trello#41]
Hi!

Since this module is number 1 at npm for `trello` I thought I'd mention that the links to generate token, app secret and app key in the readme are dead. A logged in user can generate them at [/app-key](https://trello.com/app-key). If you don't have time to update - do you accept PRs?

**Comment by norberteder** [comment]
Thank you for your feedback. Of course I do accept PRs :)

**Comment by karlpokus** [comment]
Cool. Coming up!
