### ISSUE TITLE
Create Board error

### ISSUE THREAD

**Issue by motionharvest** [norberteder/trello#61]
I just spent 2 hours trying to figure out why I couldn't create a board. I kept getting an odd error saying I didn't have permission to access the API... despite having an auth token with the proper read/write permissions.

I referenced the Trello API and noticed that the Docs use this api call "http://api.trello.com/1/boards/" and on on line 95 of main.js you are missing the trailing slash. https://github.com/norberteder/trello/blob/master/main.js#L95

I popped into node_modules and made the edit and the issue i was having vanished. First try, new board created itself no problem.

**Comment by mgaruccio** [comment]
This is actually interesting, we shouldn't need the trailing slash since there are no characters in the URL after `/1/boards`.  If it's failing I'm guessing Trello has changed their API to require the trailing slash, in which case we need to make changes to a number of functions that do not have a trailing slash.  going to test on my end and see if I'm able to reproduce the problem.

**Comment by motionharvest** [comment]
I'm doing a little more checking, just to double check i didn't misinterpret the test results.

**Comment by mgaruccio** [comment]
Just tested and I'm seeing the same strange access denied error without the trailing slash but with the trailing slash it works.  Appreciate you testing the other functions, saved me a bunch of time confirming one of my apps didn't just break.  This should be a pretty simple fix, just need to update the function and associated test, do you want to submit the PR or would you like me to?  @norberteder will ultimately need to approve either way.

**Comment by motionharvest** [comment]
I did everything except bump the version number and update the Readme

**Comment by motionharvest** [comment]
I see that my edit was merged, Can you create a new release so npm install pulls the change?

**Comment by norberteder** [comment]
Sorry for the late reply. A new version 0.9.1 is available now as npm package. Thank you very much for your contribution.
