### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by hokkqi** [norberteder/trello#71]
I can't seem to find any Docs, I'd love to use this module properly but there is no documentation to find out how something works

**Comment by norberteder** [comment]
What's missing in the README file?

**Comment by codepupper** [comment]
There's no real info on what each action/function requires unless I download it and test it myself.
~~this is just for general ease of use tbh~~

**Comment by KaptianCore** [comment]
yeah something like discordjs has done would be cool

**Comment by codepupper** [comment]
Yeah, either something like <trello>.js.org for docs or Typings for the module, though both would be best

**Comment by MG-RX93** [comment]
Can you add how List_Id is to be added or the steps to get that, please? It would be nice to have them all here together instead of going to Trello's API doc and searching through a ton of other resources

**Comment by hokkqi** [comment]
Is there an update on this? 
It's still rather cumbersome to use a module like this, without proper Docs. Right now I have to trust whatever VSC's Tooltips say and hope that it works

**Comment by hokkqi** [comment]
I honestly feel like there just won't be any docs other than the jsdoc ones you get within VSCode. I opened this issue 2 years ago and the last commit is from 10 months ago. 

I think it'd make sense to just write my own wrapper at this point tbh. 😕

**Comment by MG-RX93** [comment]
> I honestly feel like there just won't be any docs other than the jsdoc ones you get within VSCode. I opened this issue 2 years ago and the last commit is from 10 months ago.
> 
> I think it'd make sense to just write my own wrapper at this point tbh. 😕

Yeah man.

**Comment by hokkqi** [comment]
Considering this has been open for two years and there hasn't been any progress, I'm just going to close this issue.
