### ISSUE TITLE
Support Custom Fields

### ISSUE THREAD

**Issue by wallevy** [norberteder/trello#76]
https://developers.trello.com/reference#custom-fields-object

- Get/Create/Update/Delete custom fields for board
- Update the value of custom fields for card

I can do this when have time, maybe next week.

**Comment by gylidian** [comment]
also need CUSTOM FIELDS, it's such an important function

**Comment by mmunozfe** [comment]
also need custom fields!

**Comment by jwktje** [comment]
I created a PR to support custom fields. Here is an example of how I have it working; 

```
trello.updateCustomFieldOnCard(card_id, field_id, {text : 'String that needs to be set' })
```
