### ISSUE TITLE
Support Move Card To List & Copy Board

### ISSUE THREAD

**Issue by KaptianCore** [norberteder/trello#80]
Add so I can clone a board and define a name for it, and move card so I can send cards to and from boards where I can define what card & what board & what placement

**Comment by sinisterstuf** [comment]
The _"move card to list"_ to list functionality is provided by the `updateCardList` function, here's [an example from the test suite](https://github.com/norberteder/trello/blob/master/test/spec.js#L396).

I've added the _"copy board"_ functionality in pull request #82.
