### ISSUE TITLE
Ability To Send All Cards & Lists To A Board

### ISSUE THREAD

**Issue by KaptianCore** [norberteder/trello#84]
I am trying to make a script to basically clone a Trello board and if something happens to it I can just revert it with a simple command (using discord js as well) that will send all lists and cards on the original board (I am going to define the original board's id's in multiple variables. 

So basically I am asking if I can get all the lists on the board and send the lists and cards in the exact same place to another board.

Thanks

**Comment by sinisterstuf** [comment]
If I understand correctly you basically want to be able to copy a board, the same as in your other issue #80... or at least part of that issue. The copy board functionality is implemented in pull request #82 which is not yet merged.

If you're impatient for this to be merged into master, then until it is merged you can still solve your problem, as it's mentioned in the README

> Everything that is not available as a function can be requested by calling `makeRequest`.

See [the implementation from the "copy board" pull request](https://github.com/norberteder/trello/pull/82/commits/b1ab4a075285e0203a6f144c16c909b3452a4b11#diff-7a9076d6d94e62c13d641aa71f19ae8e) as an example that you could write using `makeRequest`.

**Comment by norberteder** [comment]
`copyBoard` has been merged and is already released (see 0.10.0).
