### ISSUE TITLE
Support to get customFields on Board

### ISSUE THREAD

**Issue by luiztiago** [norberteder/trello#85]
I am trying to get all `customFields` on board and currently, we don't have support for this.

Thanks

Reference:
https://developers.trello.com/reference#boardsidcustomfields

**Comment by dmarcucci** [comment]
+1 for this.

**Comment by carlitosz** [comment]
👍

**Comment by luiztiago** [comment]
😢

**Comment by norberteder** [comment]
Added in 0.10.0
