### ISSUE TITLE
Security vulnerability of qs dependency

### ISSUE THREAD

**Issue by kdekooter** [norberteder/trello#89]
According to Snyk the version of qs that is being used at the moment is not secure. 

![image](https://user-images.githubusercontent.com/508983/72878173-c1d9fa00-3cfa-11ea-895c-a26dac03f8f9.png)

Hmm. Looks like "restler" is the culprit here. And that project has not seen a commit in 4 years.

There is an outstanding issue in the restler project addressing this: https://github.com/norberteder/trello/issues/89#issue-553385100

**Comment by norberteder** [comment]
Mhm. Thank you very much.
I try to replace it as soon as possible.

**Comment by oltreseba** [comment]
I see this has been fixed but not published to npm? Is it possible to do that?

**Comment by roelsgaard** [comment]
A would also like this fix to be comitted

**Comment by adheeshfordev** [comment]
+1 . Would like to see this on npm.

**Comment by mmoomocow** [comment]
As this seems like a dead package and i need to fix this issue, i have created [This clone](https://www.npmjs.com/package/trello-new)
I've fixed this issue and its currently working. Feel free to come and check it out

**Comment by norberteder** [comment]
The fix itself wasn't tested to 100%, that's why I did not create a npm package.
@mmoomocow If it works fine I would be glad if you could provide a pull request for changes you did on this issue.

**Comment by mmoomocow** [comment]
@norberteder from my tests (both the ones set in `npm test` and testing of **some** functions) it seems to be working. However as I didn't make many changes to your fix I'll do more tests of the functions.

**Comment by davidburson** [comment]
does anyone have this fixed and working?  I get a 404 on mmoomocow's clone above.

**Comment by mmoomocow** [comment]
@davidburson I had made it private temporary. Its back to public and can be used again

**Comment by norberteder** [comment]
Fixed with Version 0.12.0.
