### ISSUE TITLE
setCardPos

### ISSUE THREAD

**Issue by WillFJS** [norberteder/trello#93]
It would be nice if you guys added a function to set the card pos.

**Comment by Costpap** [comment]
This would be extremely good and useful to have.

**Comment by Will3126** [comment]
Yeah, Maybe they could add setPos. for cards and list 🤔

**Comment by CookieTimjim** [comment]
#100 
I've created a pull request for this feature.

**Comment by Tijm-Wolters** [comment]
Resolved in #100

**Comment by WillFJS** [comment]
Merged #100
